export const LEFT_PAGE_CONTROL_ENTHUSIASM = 'LEFT_PAGE_CONTROL_ENTHUSIASM';
export type LEFT_PAGE_CONTROL_ENTHUSIASM = typeof LEFT_PAGE_CONTROL_ENTHUSIASM;

export const RIGHT_PAGE_CONTROL_ENTHUSIASM = 'RIGHT_PAGE_CONTROL_ENTHUSIASM';
export type RIGHT_PAGE_CONTROL_ENTHUSIASM = typeof RIGHT_PAGE_CONTROL_ENTHUSIASM;